---
title: "spotify_tsne"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Rtsne)
library(tidyverse)
library(caret)
library(plotly)
```

```{r input}
top2018 <- read.csv("~/git_repo/creative_coding/p5/sketches/sound/sound_flower_spotify/data/top2018.csv", stringsAsFactors=FALSE)
```

```{r pre-process}
df <- top2018 %>% select(danceability:duration_ms)
```

```{r scale}
preObj <- preProcess(df, method=c("scale"))
df_scaled <- predict(preObj, df)
```


```{r tsne}
set.seed(100)
fit.tsne <- Rtsne(df_scaled, dims = 2, perplexity=15, verbose=TRUE, max_iter = 500)


d_tsne <- data.frame(fit.tsne$Y, Class = top2018$name)
colnames(d_tsne) <- c("x", "y", "name")



my_theme <- function(base_size = 12, base_family = "Helvetica") {
    theme_minimal() +
    theme(axis.title.y = element_blank(),axis.title.x = element_blank(),
    plot.title = element_text(face = "bold", size = 16),
    plot.background = element_rect(fill = 'ghostwhite',color='white'),
    text = element_text(family = "Helvetica"),
    panel.grid.major.y = element_blank(),panel.grid.minor.y = element_blank(),
    legend.position = 'None')
}

d_tsne %>%
  ggplot(aes(x, y, col=name)) + geom_point() + 
  ggtitle('t-sne on spotify song attributes') + my_theme()
```

```{r post-process}
#re-merge with original data
df_output <- top2018 %>% 
  left_join(d_tsne, by='name')
```

```{r}
write.csv(df_output, 'df_output_tsne.csv')
```

